spring:
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://PGYUSER
        predicates:
        - Path=/user/**
      - id: PGY-SPRING-CLOUD-USER
        uri: lb://PGYUSER
        predicates:
        - Path=/actuator/info/**
  application:
    name: pgygateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck.enabled: true
    registerWithEureka: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug